# These are supported funding model platforms

ko_fi: v1rtl
liberapay: v1rtl
custom: ["https://paypal.me/v1rtl", "https://qiwi.com/n/V1RTL", "https://yoomoney.ru/to/410014774355272"]
issuehunt: talentlessguy
