ko_fi: v1rtl
liberapay: v1rtl
custom: ["https://v1rtl.site/support", "https://giveth.io/project/tinyhttp", "https://drips.network/app/projects/github/tinyhttp/tinyhttp"]
issuehunt: talentlessguy
github: [tinyhttp, talentlessguy, aldy505, rocktimsaikia]
