packages:
  - "packages/*"

catalog:
  "@tinyhttp/content-type": ^0.1.4
  header-range-parser: 1.1.4
  mrmime: ^2.0.1
  regexparam: ^3.0.0

trustPolicy: no-downgrade

minimumReleaseAge: 1440
trustPolicyIgnoreAfter: 10080
allowBuilds:
  esbuild: true
